version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      
  # django:
  #   build: ./backend/services/django
  #   command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - ./backend/services/django:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres

  node:
    build: ./backend/services/node
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
