version: '3.8'

services:
  frontend:
    image: ghcr.io/pearlpandz/creavo/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      
  django:
    image: ghcr.io/pearlpandz/creavo/django
    build: ./backend/services/django
    command: /app/entrypoint.sh
    volumes:
      - ./backend/services/django:/app
    ports:
      - "8000:8000"

  node:
    image: ghcr.io/pearlpandz/creavo/node
    build: ./backend/services/node
    ports:
      - "4000:4000"

