name: Build and Push to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Images
        run: docker compose -f docker-compose.yml build --build-arg IMAGE_TAG=${{ secrets.IMAGE_TAG }}

      - name: Push Docker Images
        run: docker compose -f docker-compose.yml push

      # - name: Run Docker Compose
      #   run: |
      #     docker-compose -f docker-compose.yml up -d
      #   env:
      #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      #     POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
